server {
        listen 80;
        listen [::]:80;
        server_name prometheus.bui-van-tuan-lam.com;
        return 301  https://$host$request_uri;
}

server {
        listen 443 ssl;
        listen [::]:443 ssl;

        server_name prometheus.bui-van-tuan-lam.com;

        ssl_certificate /etc/nginx/ssl/bui-van-tuan-lam.com.crt;
        ssl_certificate_key /etc/nginx/ssl/bui-van-tuan-lam.com.key;

        location / {
                proxy_pass  http://0.0.0.0:9090;
                include proxy_params;

                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
        }
}
